export interface Product {
  id: string
  name: string
  category: string
  price: number
  rating: number
  reviews: number
  image: string
  description: string
  specs: string[]
  inStock: boolean
}

export const products: Product[] = [
  {
    id: "1",
    name: "Minimal Leather Watch",
    category: "Accessories",
    price: 380,
    rating: 4.8,
    reviews: 142,
    image: "/luxury-minimal-leather-watch-black-face.jpg",
    description: "Timeless elegance meets precision engineering. Handcrafted with premium Italian leather.",
    specs: ["Swiss Movement", "Sapphire Crystal", "50M Water Resistant", "Italian Leather Strap"],
    inStock: true,
  },
  {
    id: "2",
    name: "Premium Wireless Earbuds",
    category: "Technology",
    price: 299,
    rating: 4.9,
    reviews: 328,
    image: "/premium-black-wireless-earbuds-luxury.jpg",
    description: "Crystal-clear sound with active noise cancellation and 12-hour battery life.",
    specs: ["Active Noise Cancellation", "12H Battery", "Wireless Charging", "IP54 Water Resistant"],
    inStock: true,
  },
  {
    id: "3",
    name: "Geometric Marble Pen",
    category: "Stationery",
    price: 85,
    rating: 4.7,
    reviews: 89,
    image: "/luxury-marble-pen-geometric-design.jpg",
    description: "Handcrafted writing instrument with genuine marble accents and precision nib.",
    specs: ["Genuine Marble", "German Engineering", "Refillable Design", "Premium Packaging"],
    inStock: true,
  },
  {
    id: "4",
    name: "Carbon Fiber Wallet",
    category: "Accessories",
    price: 145,
    rating: 4.6,
    reviews: 76,
    image: "/carbon-fiber-slim-wallet-black-modern.jpg",
    description: "Ultra-slim, RFID-protected wallet engineered with lightweight carbon fiber.",
    specs: ["RFID Protection", "Carbon Fiber Body", "12 Card Slots", "Lifetime Warranty"],
    inStock: true,
  },
  {
    id: "5",
    name: "Minimalist Desk Lamp",
    category: "Home",
    price: 220,
    rating: 4.8,
    reviews: 167,
    image: "/minimalist-desk-lamp-modern-black-white.jpg",
    description: "Adjustable LED desk lamp with touch control and premium aluminum construction.",
    specs: ["Touch Dimming", "USB Charging Port", "Memory Settings", "360° Articulation"],
    inStock: true,
  },
  {
    id: "6",
    name: "Ceramic Coffee Set",
    category: "Home",
    price: 165,
    rating: 4.5,
    reviews: 94,
    image: "/premium-ceramic-coffee-set-modern.jpg",
    description: "Handmade ceramic set with porcelain finish. Includes kettle, cups, and saucers.",
    specs: ["Handmade Ceramic", "Porcelain Glaze", "Dishwasher Safe", "Thermal Resistant"],
    inStock: true,
  },
  {
    id: "7",
    name: "Titanium Phone Mount",
    category: "Technology",
    price: 95,
    rating: 4.7,
    reviews: 203,
    image: "/titanium-phone-mount-car-minimalist.jpg",
    description: "Universal phone mount crafted from aerospace-grade titanium alloy.",
    specs: ["Titanium Alloy", "Universal Fit", "360° Rotation", "Non-Slip Grips"],
    inStock: true,
  },
  {
    id: "8",
    name: "Linen Storage Box",
    category: "Home",
    price: 110,
    rating: 4.4,
    reviews: 58,
    image: "/natural-linen-storage-box-minimalist.jpg",
    description: "Sustainable linen storage solution with magnetic closures and elegant design.",
    specs: ["100% Natural Linen", "Magnetic Closure", "Collapsible", "Eco-Friendly"],
    inStock: true,
  },
  {
    id: "9",
    name: "Premium Sunglasses",
    category: "Accessories",
    price: 325,
    rating: 4.8,
    reviews: 245,
    image: "/luxury-minimal-sunglasses-black.jpg",
    description: "UV-protected lenses with titanium frames. Timeless design meets modern comfort.",
    specs: ["100% UV Protection", "Titanium Frame", "Anti-Reflective", "Lifetime Replacement"],
    inStock: true,
  },
  {
    id: "10",
    name: "Wireless Charging Pad",
    category: "Technology",
    price: 79,
    rating: 4.6,
    reviews: 412,
    image: "/minimalist-wireless-charging-pad.jpg",
    description: "Fast-charging wireless pad with premium matte finish and universal compatibility.",
    specs: ["15W Fast Charge", "Matte Finish", "Thermal Control", "LED Indicator"],
    inStock: true,
  },
  {
    id: "11",
    name: "Silk Eye Mask",
    category: "Wellness",
    price: 62,
    rating: 4.9,
    reviews: 521,
    image: "/luxury-silk-eye-mask-sleep.jpg",
    description: "Hypoallergenic silk eye mask with adjustable strap for perfect comfort.",
    specs: ["100% Mulberry Silk", "Hypoallergenic", "Adjustable Fit", "Travel Case Included"],
    inStock: true,
  },
  {
    id: "12",
    name: "Minimalist Notebook",
    category: "Stationery",
    price: 38,
    rating: 4.5,
    reviews: 134,
    image: "/premium-minimalist-notebook-black.jpg",
    description: "FSC-certified paper with genuine leather binding and ribbon bookmark.",
    specs: ["FSC-Certified Paper", "Leather Binding", "200 Pages", "Ribbon Bookmark"],
    inStock: true,
  },
]

export const categories = ["All", "Technology", "Accessories", "Home", "Stationery", "Wellness"]
export const priceRanges = [
  { label: "Under $50", min: 0, max: 50 },
  { label: "$50 - $150", min: 50, max: 150 },
  { label: "$150 - $300", min: 150, max: 300 },
  { label: "$300+", min: 300, max: Infinity },
]
